version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_HOST=192.168.10.100
      - DATABASE_PORT=5432
      - POSTGRES_DB=netguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    network_mode: host
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_HOST=192.168.10.100
      - DATABASE_PORT=5432
      - POSTGRES_DB=netguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456